import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
import { gapiLogin, gapiLogout } from './authAPI';

export interface AuthState {
    account: any;
    status: 'idle' | 'loading' | 'failed';
}

const initialState: AuthState = {
    account: null,
    status: 'idle',
};

export const login = createAsyncThunk(
    'auth/login',
    async () => {
        const response = await gapiLogin();
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const logout = createAsyncThunk(
    'auth/logout',
    async () => {
        const response = await gapiLogout();
        // The value we return becomes the `fulfilled` action payload
        return response.data;
    }
);

export const authSlice = createSlice({
    name: 'auth',
    initialState,
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(login.pending, (state) => {
                state.status = 'loading';
            })
            .addCase(login.fulfilled, (state, action) => {
                state.status = 'idle';
                state.account = action.payload;
            });
    },
});

export const selectAuth = (state: RootState) => state.auth.account;

export default authSlice.reducer;
